### ISSUE TITLE
这个地址是不是无效了：http://82.157.10.108:8086

### ISSUE THREAD

**Issue by lwinhong** [yize8888/maotai#30]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f907550df90>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='82.157.10.108', port=8086): Max retries exceeded with url: /get_mtv?DeviceID=52780558-4A7B-40D4-8407-B708CC14AC49&MTk=1705457588721&version=1.5.6&key=yaohuo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f907550df90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/yize8888_maotai/imaotai.swap.py", line 301, in <module>
    res = mt_add(itemCode, str(shop_id), sessionId,
  File "/ql/data/scripts/yize8888_maotai/imaotai.swap.py", line 35, in mt_add
    r = requests.get(
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)

**requests.exceptions.ConnectionError: HTTPConnectionPool(host='82.157.10.108', port=8086): Max retries exceeded with url: /get_mtv?DeviceID=52780558-4A7B-40D4-8407-B708CC14AC49&MTk=1705457588721&version=1.5.6&key=yaohuo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f907550df90>: Failed to establish a new connection: [Errno 111] Connection refused'))**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/yize8888_maotai/imaotai.swap.py", line 315, in <module>
    s += userName + '_' + mobile + "异常信息"+e
TypeError: can only concatenate str (not "ConnectionError") to str

**Comment by heweihao** [comment]
拉最新代码
