### ISSUE TITLE
不能用了吗？

### ISSUE THREAD

**Issue by wei209** [yize8888/maotai#32]
## 开始执行... 2024-01-19 09:41:59

Traceback (most recent call last):
  File "/ql/data/scripts/yize8888_maotai/imaotai.py", line 25, in <module>
    res_map = json.loads(os.getenv('iMT_Products', ''))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sanmuhub** [comment]
一、检查依赖，
二、检查环境变量设置，
基本上都能解决
