### ISSUE TITLE
青龙运行Traceback (most recent call last):

### ISSUE THREAD

**Issue by juzi0331** [yize8888/maotai#33]
## 开始执行... 2024-01-20 15:15:03

Traceback (most recent call last):
  File "/ql/data/scripts/yize8888_maotai/imaotai.py", line 25, in <module>
    res_map = json.loads(os.getenv('iMT_Products', ''))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## 执行结束... 2024-01-20 15:15:03  耗时 1 秒　　　
正确的添加了MTTokenD,Mt_Version

**Comment by sanmuhub** [comment]
检查MTTokenD格式
