### ISSUE TITLE
青龙面板2.7.14中报错

### ISSUE THREAD

**Issue by poctopus** [yize8888/maotai#53]
看报错都是json解析有问题，但是安装json依赖是失败的。不知道要怎么搞。
MTTokenD：上海,上海市,121.33333,31.33333,E3792FCF-CB0B-3333-B6B9-59672703E667,eyJ0eXAiOiJKV1QiLidXNlcklkIjoxMTI2ODk2MDg4LCJkZXZpY2VJZCI6IkUzNzkyRkNGLUNCMEItNEQ1Ni1CNkI5LTU5NjcyNzAzRTY2NyIsImlhdCI6MTcxNDM3NTAxOX0.5d4dYP7agt9vjBcUGPj56UhZ7F5DfNE1rb-hBgPfKxA,eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOZmY2UtNDczZS05MGZjLTJkNWIyMWEzNzZiYyIsImlhdCI6MTcxNDM3NTU4MH0._hAPfO5_qVo2Z-jb2m-s3djfnmnzgSyRutC173ldpdo

## 开始执行... 2024-04-30 09:02:25

{'10941': '贵州茅台酒（甲辰龙年）', '10942': '贵州茅台酒（甲辰龙年）x2'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/yize8888_maotai/imaotai.py", line 297, in <module>
    shop_id = get_shop_item(
  File "/ql/data/scripts/yize8888_maotai/imaotai.py", line 115, in get_shop_item
    data = response.json().get('data', {})
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/yize8888_maotai/imaotai.py", line 313, in <module>
    s += userName + '_' + mobile + "异常信息"+e
TypeError: can only concatenate str (not "JSONDecodeError") to str

**Comment by poctopus** [comment]
搞定了，原来是省字段的问题，直辖市要写上海市，不能写上海。少数民族的省份，也要填写完整的。
