### ISSUE TITLE
pycryptodome安装失败咋办，ql 2.10.13

### ISSUE THREAD

**Issue by mm2040** [yize8888/maotai#61]
开始安装依赖 pycryptodome，开始时间 2024/8/25 下午12:05:52

Collecting pycryptodome

  Using cached pycryptodome-3.20.0.tar.gz (4.8 MB)

  Installing build dependencies: started

  Installing build dependencies: finished with status 'error'

  ERROR: Command errored out with exit status 2:
   command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5wpwxxen/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools
       cwd: None
  Complete output (58 lines):
  Collecting setuptools
    Downloading setuptools-73.0.1-py3-none-any.whl (2.3 MB)
  ERROR: Exception:
  Traceback (most recent call last):
    File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 437, in _error_catcher
      yield
    File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 519, in read
      data = self._fp.read(amt) if not fp_closed else b""
    File "/usr/lib/python3.8/site-packages/cachecontrol/filewrapper.py", line 62, in read
      data = self.__fp.read(amt)
    File "/usr/lib/python3.8/http/client.py", line 455, in read
      n = self.readinto(b)
    File "/usr/lib/python3.8/http/client.py", line 499, in readinto
      n = self.fp.readinto(b)
    File "/usr/lib/python3.8/socket.py", line 669, in readinto
      return self._sock.recv_into(b)
    File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
      return self.read(nbytes, buffer)
    File "/usr/lib/python3.8/ssl.py", line 1099, in read
      return self._sslobj.read(len, buffer)
  socket.timeout: The read operation timed out
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
      status = self.run(options, args)
    File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
      return func(self, options, args)
    File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 332, in run
      requirement_set = resolver.resolve(
    File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
      discovered_reqs.extend(self._resolve_one(requirement_set, req))
    File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
      abstract_dist = self._get_abstract_dist_for(req_to_install)
    File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
      abstract_dist = self.preparer.prepare_linked_requirement(req)
    File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement
      local_file = unpack_url(
    File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 255, in unpack_url
      file = get_http_url(
    File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 129, in get_http_url
      from_path, content_type = _download_http_url(
    File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 281, in _download_http_url
      for chunk in download.chunks:
    File "/usr/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 166, in iter
      for x in it:
    File "/usr/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 15, in response_chunks
      for chunk in response.raw.stream(
    File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 576, in stream
      data = self.read(amt=amt, decode_content=decode_content)
    File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 541, in read
      raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
    File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 442, in _error_catcher
      raise ReadTimeoutError(self._pool, None, "Read timed out.")
  urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
  ----------------------------------------

ERROR: Command errored out with exit status 2: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5wpwxxen/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools Check the logs for full command output.

**Comment by mm2040** [comment]
知道了，需要重新安装wheels
